name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: redfyel/contrib-pie-generator/.github/workflows/main.yml@v2.1
    with:
      chart-size: '6,6'
