name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: redfyel/contrib-pie-generator/.github/workflows/main.yml@v2.300
    with:
      chart-size: '6,6'
      palette: "#0A122A, #698F3F, #E7DECD"
