name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: redfyel/contrib-pie-generator/.github/workflows/main.yml@v0
    with:
      chart-size: '5,5'
      palette: "#0A122A, #698F3F, #E7DECD"
      repo-url: "https://api.github.com/repos/redfyel/dishcovery/contributors"
