name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: redfyel/contrib-pie-generator/.github/workflows/main.yml@v1.5
    with:
      chart-size: '7,7'  
